### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghazouani1212** [bendingthemrules/ubtouch-element#1]
The application stopped working after logging in. It freezes on the settings page and flashes
![screenshot20230316_105342744](https://user-images.githubusercontent.com/128038235/225580806-731384c4-1169-46b4-8481-ec6c645f21a7.png)

**Comment by Vuurvos1** [comment]
Thanks for leaving this issue, the problem should be resolved in the latest update

**Comment by Written0489** [comment]
Hi, this is happening to me on the latest version available from OpenStore on focal. It opens straight to the "Sidebar" tab of the settings modal. Clicking the X on the modal reopens the menu instantly, clicking any of the other tabs in the settings jumps straight back to the Sidebar tab. If you try to scroll down on the modal it jumps back up to the top.
